wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1654852788
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      4: 3.8.11
      5: 0.12.17
      8:
      - 5
batch_norm:
  desc: null
  value: true
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.35
epoch:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.0001
